#!/usr/bin/python3

import argparse
import sys

def do_repo(args):
    args.subfunc(args)

def do_repo_add(args):
    print('repo add', args.path)

def do_repo_rm(args):
    print('repo rm', args.path)

def do_pull(args):
    print('pull', args)
    pass

def do_push(args):
    print('push', args)
    pass

if __name__ == '__main__':
    root_parser = argparse.ArgumentParser(prog = 'gitgit', 
            description = 'git getting utility')
    subparsers = root_parser.add_subparsers()

    repo_parser = subparsers.add_parser('repo', help='respository to gitgit')
    repo_parser.set_defaults(func = do_repo)
    repo_sub = repo_parser.add_subparsers()

    repo_add = repo_sub.add_parser('add', help='add repository')
    repo_add.set_defaults(subfunc = do_repo_add)

    repo_rm = repo_sub.add_parser('rm', help='remove repository')
    repo_rm.set_defaults(subfunc = do_repo_rm)

    repo_parser.add_argument('path', type=str, default = '.')

    pull_parser = subparsers.add_parser('pull', help='pull tracked repositories')
    pull_parser.set_defaults(func = do_pull)

    push_parser = subparsers.add_parser('push', help='push tracked repositories')
    push_parser.set_defaults(func = do_push)

    args = root_parser.parse_args(sys.argv[1:])
    args.func(args)

